# StartupAI CrewAI Task Configurations
# Value Proposition Design Crew - 6 Core Tasks
# Transforms startup ideas into validated, evidence-based value propositions

onboarding_task:
  description: |
    Conduct an onboarding session with the entrepreneur to create an Entrepreneur Brief.
    Ask questions that clarify:
      - Customer segment and core problem
      - Product or solution vision
      - Key differentiators
      - Competitors (if any)
      - Target channels and assets available
      - Budget and timeline for validation
    Summarize these in a structured JSON format.
  expected_output: |
    A complete Entrepreneur Brief JSON with clear and concise founder input including:
    - Target customer segment description
    - Core problem statement
    - Product/solution vision
    - Key differentiators from competitors
    - Available channels and marketing assets
    - Budget constraints and validation timeline
  agent: onboarding_agent

customer_research_task:
  description: |
    Based on the Entrepreneur Brief, research the target customer profile.
    Identify jobs, pains, and gains and compile them into a Customer Profile.
    
    Focus on:
    - Customer Jobs: What tasks are customers trying to accomplish?
    - Customer Pains: What obstacles prevent them from completing jobs?
    - Customer Gains: What positive outcomes do they hope to achieve?
    
    Use secondary research, industry reports, and logical inference based on
    the customer segment described in the Entrepreneur Brief.
  expected_output: |
    A structured Customer Profile document (Jobs, Pains, Gains)
    formatted for integration into the Value Proposition Canvas:
    - Customer Jobs (functional, social, emotional)
    - Customer Pains (undesired outcomes, obstacles, risks)
    - Customer Gains (required, expected, desired, unexpected)
  agent: customer_researcher

competitor_analysis_task:
  description: |
    Analyze direct and indirect competitors based on the Entrepreneur Brief.
    Build a Positioning Map and describe strategic differentiation opportunities.
    
    Focus on:
    - Identifying 3-5 key competitors (direct and indirect)
    - Analyzing their value propositions and business models
    - Mapping competitive positioning on key dimensions
    - Identifying white space opportunities
    - Recommending differentiation strategies
  expected_output: |
    A Competitor Analysis Report and a Positioning Map highlighting:
    - Competitor profiles (value props, business models, strengths/weaknesses)
    - Competitive positioning visualization
    - White space opportunities in the market
    - Strategic differentiation recommendations
    - Competitive threats and opportunities
  agent: competitor_analyst

value_design_task:
  description: |
    Combine the Customer Profile and Competitor Analysis to create a Value Proposition Canvas.
    Draft a clear Value Proposition Statement summarizing the unique value created.
    
    Focus on:
    - Products & Services: What does the startup offer?
    - Pain Relievers: How does the offering alleviate customer pains?
    - Gain Creators: How does the offering create customer gains?
    - Value Proposition Statement: One clear sentence articulating the unique value
    
    Ensure the value proposition is differentiated based on competitor analysis.
  expected_output: |
    A Value Proposition Canvas (Customer Profile + Value Map) and a concise
    Value Proposition Statement suitable for validation:
    - Complete Value Map (products/services, pain relievers, gain creators)
    - Value Proposition Statement (one compelling sentence)
    - Differentiation rationale vs competitors
    - Fit assessment between Customer Profile and Value Map

validation_task:
  description: |
    Develop a Validation Roadmap composed of three evidence tiers:
      - Weak evidence test: fast, low-cost signal
      - Medium evidence test: moderate budget, deeper validation
      - Strong evidence test: commitment-based proof
    Each test should reference a specific assumption and describe expected outcomes.
    
    Focus on:
    - Identifying key assumptions from the Entrepreneur Brief and Value Proposition
    - Designing experiments using the "Testing Business Ideas" framework
    - Categorizing tests by evidence strength and resource requirements
    - Defining success metrics and learning objectives for each test
  expected_output: |
    A 3-tier Validation Roadmap with experiments categorized as weak, medium,
    or strong evidence tests linked to assumptions in the evidence ledger:
    - Weak Evidence Tests (smoke tests, landing pages, interviews)
    - Medium Evidence Tests (prototypes, concierge MVP, pre-orders)
    - Strong Evidence Tests (pilot programs, committed purchases, LOIs)
    - Each experiment includes: assumption tested, method, budget, timeline, success criteria
  agent: validation_agent

qa_task:
  description: |
    Review all deliverables (Entrepreneur Brief, Customer Profile, Positioning Map,
    Value Proposition Canvas, Validation Roadmap). Ensure compliance with the frameworks:
      - Value Proposition Design
      - Testing Business Ideas
      - Business Model Generation
    
    Focus on:
    - Framework compliance: Do deliverables follow best practices?
    - Logical consistency: Are there contradictions or gaps?
    - Actionability: Can the entrepreneur act on these deliverables?
    - Quality standards: Do outputs meet professional consulting standards?
    - Refinement suggestions: What improvements would increase value?
  expected_output: |
    A QA Report summarizing:
    - Framework compliance assessment (Value Prop Design, Testing Business Ideas, BMG)
    - Logical consistency check (gaps, contradictions, missing elements)
    - Actionability rating (can founder implement recommendations?)
    - Quality score (professional consulting standards)
    - Suggested refinements for each deliverable
    - Pass/fail recommendation for client delivery
  agent: qa_agent
